TrajectoryPlannerROS:
  acc_lim_x: 0.8      # Maximum linear acceleration (meters/sec^2)
  acc_lim_theta: 1.0  # Maximum rotating acceleration (radians/sec^2)
  max_vel_x: 0.2      # Maximum linear velocity (meters/sec)
  min_vel_x: 0.1      # Minimum linear velocity (meters/sec)
  max_vel_theta: 1.0  # Maximum rotating velocity (radians/sec)
  min_vel_theta: -1.0 # Minimum rotating velocity (radians/sec)
  min_in_place_vel_theta: 1.0 # Minimum in-place rotating velocity (radians/sec)
  holonomic_robot: false
  yaw_goal_tolerance: 0.5
  xy_goal_tolerance: 0.1
  path_distance_bias: 1.0
  goal_distance_bias: 1.0 
  occdist_scale: 0.05
  meter_scoring: true
  sim_granularity: 0.04
